package io.github.saul789.api.standard.exception;

import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to specify a custom problem type URI (the {@code type} field in RFC 9457 Problem
 * Detail).
 *
 * <p>Can be placed on custom exception classes to override the default URI generated by the starter
 * ({@code typeBaseUri} + kebab-case code).
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Inherited
public @interface ProblemType {
  /**
   * The custom problem type URI.
   *
   * <p>e.g. {@code "https://example.com/errors/not-enough-funds"}
   */
  String value();
}
