name: CI - Build & Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:25-jdk 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Maven
        run: |
          apt-get update
          apt-get install -y maven

      - name: Build, Test & Coverage
        run: mvn clean verify -B jacoco:report

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'spring-boot-starter-api-standard'
          scan: '.'
          format: 'HTML'

      - name: SpotBugs + FindSecBugs
        run: |
          mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.8.2:check \
              -Dspotbugs.failOnError=true

      - name: PMD Analysis
        run: mvn pmd:pmd

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: "**/target/site/jacoco/**"

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check
          path: "**/dependency-check-report.*"